### ISSUE TITLE
Interest in Array-Based Fork

### ISSUE THREAD

**Issue by cwfitzgerald** [F3kilo/ktx2-reader#1]
Hello! Thank you for writing this library!

As I do not use tokio, and I saw that it was on your TODO list, I refactored the library [in a fork](https://github.com/BVE-Reborn/ktx2-reader) to use `T: AsRef<[u8]>` for its internal data type and completely shed tokio as a non-dev dependency. Would you be interested in seeing this upstreamed? The fork still needs a bit of error-related work but is otherwise working fine.

**Comment by F3kilo** [comment]
> Hello! Thank you for writing this library!
> 
> As I do not use tokio, and I saw that it was on your TODO list, I refactored the library [in a fork](https://github.com/BVE-Reborn/ktx2-reader) to use `T: AsRef<[u8]>` for its internal data type and completely shed tokio as a non-dev dependency. Would you be interested in seeing this upstreamed? The fork still needs a bit of error-related work but is otherwise working fine.

Hello! I'm happy about someone find this library useful. I think it's a good addition.

**Comment by F3kilo** [comment]
Merged
